[project]
name = "anti-counterfeit-drug-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.14",
    "typing>=3.10.0.0",
]
